version: '3'

services:
  # postgres
  db:
    image: postgres:12
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=movies
      - POSTGRES_PASSWORD=movies

  # django admin panel
  admin:
    depends_on:
      - db
    build:
      context: movie_admin
    volumes:
      - static:/code/static
    env_file:
      - movie_admin/.env

  # the bleeding edge server
  web:
    image: nginx:1.20
    depends_on:
      - admin
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/site.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/var/www/site/static
    ports:
      - "8000:80"

  etl:
    image: elasticsearch:7.7.0
    environment:
      discovery.type: single-node
    logging:
      driver: none

volumes:
  static:
  pgdata: