# Generated by Django 3.1 on 2021-04-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='filmworkperson',
            name='role',
            field=models.CharField(choices=[('writer', 'сценарист'), ('director', 'режиссер'), ('actor', 'актер')], max_length=255, verbose_name='профессия'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='полное имя'),
        ),
    ]
