# Generated by Django 3.1 on 2021-05-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_admin', '0002_auto_20210427_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата выхода'),
        ),
    ]
