# Generated by Django 3.1 on 2021-05-09 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_admin', '0003_filmwork_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmworkgenre',
            old_name='film_work_id',
            new_name='film_work',
        ),
        migrations.RenameField(
            model_name='filmworkgenre',
            old_name='genre_id',
            new_name='genre',
        ),
    ]
