# Generated by Django 3.1 on 2021-05-14 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_admin', '0004_auto_20210509_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='filmworkperson',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='modified',
        ),
        migrations.AddField(
            model_name='filmwork',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='filmworkperson',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='filmworkgenre',
            name='film_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_genres', to='movie_admin.filmwork'),
        ),
        migrations.AlterField(
            model_name='filmworkperson',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='filmworkgenre',
            unique_together={('film_work_id', 'genre_id')},
        ),
    ]
